### ISSUE TITLE
예약, 주문 메인 페이지 그리기

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-bo#12]
## Feature Description
- 예약, 주문 메인 페이지 그리기

## Todo list

- [x] 예약, 주문 메인 페이지 그리기
- [x] 샘플 API 데이터 생성
- [ ] 재사용할 수 있는 컴포넌트 분리 (표 등)
