### ISSUE TITLE
팝업스토어 예약 인원 수 업데이트 구현

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-bo#47]
## Feature Description
- 팝업스토어 예약 인원 수 업데이트 구현

## Todo list

- [x] 예약 대기 상태의 예약만 수정할 수 있도록 아이콘을 표시한다.
- [x] 연필 아이콘을 누르면 수정 다이얼로그 창이 뜨도록 한다.
- [x] 확인 버튼/엔터를 누르면 업데이트 API를 호출한다.
- [x] 확인을 누르면 다이얼로그 창이 종료되고, 변경된 값이 테이블에 반영된다.
