### ISSUE TITLE
예약 중단 및 재개 구현

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-bo#54]
## Feature Description
- 예약 대기 상태의 예약을 중단한다.
- 중단된 예약 상태를 재개한다.

## Todo list

- [x] 예약 대기 상태의 버튼을 hover하면 예약 중단로 변경된다.
- [x] 예약 대기 상태 버튼을 누르면 취소 확인 여부의 다이얼로그가 뜬다.
- [x] 확인 버튼을 누르면 해당 예약이 중단된다.
- [x] 예약 중단 상태의 버튼을 누르면 예약 재개 다이얼로그가 뜬다.
- [x] 확인 버튼을 누르면 해당 예약이 재개된다.
