### ISSUE TITLE
일일 예약 내역 그리기

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-bo#6]
## Feature Description
- 일일 예약 내역 그리기

## Todo list

- [x] 일일 예약 내역 그리기
- [x] 샘플 데이터 생성하기
- [x] 재사용할 커튼 컴포넌트 생성
- [x] API 연동 시 대체할 textField 구분
