### ISSUE TITLE
백오피스 디자인 수정

### ISSUE THREAD

**Issue by WoowonKim** [bone-stew/popmate-bo#90]
## Feature Description
- 

## Todo list

- [ ] 헤더 폰트 크기 증가
- [ ] 일일 상세 내역 헤더 추가
- [ ] 스토어 등록 버튼 추가
